### ISSUE TITLE
Add unit test for deleting a Camel Route

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1007]
### Please describe the task that needs to be done

Follow up of https://github.com/KaotoIO/kaoto-next/issues/974

After merging https://github.com/KaotoIO/kaoto-next/pull/1003, we need to add a unit test to cover this newly added functionality.

**Comment by shivamG640** [comment]
Added tests here: https://github.com/shivamG640/kaoto-next/blob/Fix_1007/packages/ui/src/components/Visualization/Canvas/Canvas.test.tsx#L45-L113

Marking this as blocked as we are unable to delete the route/kamelet container just by clicking on the `Delete` contextMenuIteam!
