### ISSUE TITLE
Add a container for Pipes

### ISSUE THREAD

**Issue by shivamG640** [KaotoIO/kaoto#1031]
### Please describe the feature that you want to propose

Add container for Pipes, Just like we have for Routes and Kamelet.

**Comment by lordrip** [comment]
We need to define the most common properties from a Pipe to offer them through the CanvasForm

**Comment by lordrip** [comment]
Here's the `Pipe` spec: https://camel.apache.org/camel-k/2.3.x/apis/camel-k.html#_camel_apache_org_v1_PipeSpec

So far I can't see any special field, so we can show the following items, similar to `Kamelets`
* Name
* Labels
* Annotations
