### ISSUE TITLE
Warn users when trying to delete a container step

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto#1042]
If a user tries to delete a canvas step which has children, we should display a confirmation / warning modal dialog, informing the user that they are about to delete a step that contains children and asking for confirmation. It could be handy to also display the amount of child elements affected by that delete to make it even more clear.

`You are about to delete a step which contains <number> child elements. All the elements will be deleted as well. Do you want to proceed?`

This handling also needs to be applied when deleting routes, kamelets and pipes (once available).

**Comment by shivamG640** [comment]
Since I added the container deletion functionality, assigning this to myself!
