### ISSUE TITLE
Focus is lost on field after coming from Help message

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1080]
### Describe the Bug

when the help message is opened, then clicking on a field is closing the help message, briefly setting focus on the field to edit then changing the focus back to the Help icon

### Steps to Reproduce the Bug or Issue

1. create a camel route
2. select a step
3. click on the help icon of a field
4. click in a text field

### Screenshots or Videos

https://github.com/KaotoIO/kaoto/assets/1105127/6f5cca77-ed0c-496e-bb1a-aadb7a10cfc2

### Platform

- OS: Linux
- Browser: Firefox
- Version: 2.0.0-RC2

**Comment by d4n1b** [comment]
In addition to that, it gets even funkier (🥳🪩) when you use the tab key:

https://github.com/user-attachments/assets/62c9f3e1-44b4-4244-8a4f-11ec8e852714

**Comment by lhein** [comment]
Scary, thanks for the footage!

**Comment by d4n1b** [comment]
Hola 👋  - I create∂ a PR to fix this issue: https://github.com/KaotoIO/uniforms-patternfly/pull/146
