### ISSUE TITLE
Support different Camel catalog versions

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1109]
### Please describe the feature that you want to propose

Currently, Kaoto uses a predefined upstream Camel catalog version. The goal for this issue is to support different Camel catalog versions.

Here's a rough plan for doing so:

- [X] Update the Kaoto catalog index.json file https://github.com/KaotoIO/kaoto/pull/1111 (https://github.com/KaotoIO/kaoto/issues/5)
- [X] Create a new maven package to generate multiple catalogs (catalog library) https://github.com/KaotoIO/kaoto/pull/1169
- [X] Adapt UI to accommodate the newly generated catalog library https://github.com/KaotoIO/kaoto/pull/1182
- [X] Settings page to set the catalog URL https://github.com/KaotoIO/kaoto/pull/1201 (https://github.com/KaotoIO/kaoto/issues/834)
- [X] Support for productized version of CEQ and CSB https://github.com/KaotoIO/kaoto/pull/1238
- [x] https://github.com/KaotoIO/vscode-kaoto/pull/605 (#1204)
- [X] Update the demo catalog https://github.com/KaotoIO/catalogs/pull/3
- [ ] Filter components by Provider https://github.com/KaotoIO/kaoto/pull/1239

**Comment by lhein** [comment]
we should move away from using `kaoto-next`.

**Comment by lordrip** [comment]
where did you see it? I saw the title of the previous GH issue and renamed it.
