### ISSUE TITLE
Implement BaseVisualCamelEntity for Integration CRD

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#113]
### Context
Currently, there's only support to render Camel Routes in the `Design` section of kaoto-next.

### Goal
This issue aims to implement a `BaseVisualCamelEntity` for the `Integration` CRD.

### Notes
* [Camel Route Example](https://github.com/KaotoIO/kaoto-next/blob/c633b07c419fad48f0e4b65b3f4a0687819aa4ba/packages/ui/src/models/camel-entities/flows/route.ts)

* After building `kaoto-next/packages/camel-catalog`, using `yarn workspace @kaoto-next/camel-catalog run build`, you will find the `Integration` CRD JSON Schema in `packages/camel-catalog/dist/crd-schema-integrations-2.1.0-SNAPSHOT.json`

* You could use a Typescript definition for `Integration` like:
```typescript
import { Integration } from '@kaoto-next/camel-catalog/types';
```

**Comment by apupier** [comment]
with Camel K deprecation, there is no plan to work on this issue anymore
