### ISSUE TITLE
Vectorize Golden Camel so we can use it in many places

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1150]
### Please describe the feature that you want to propose

Currently, the golden camel 🐪 is a PNG based file, the idea is to have a vector version of it, so we can embed it on several places and more important, to reduce the file size.

**Comment by d4n1b** [comment]
_Hola_ 👋 

<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZW1ud3MyZWVuc2x5ejhqZTkzcWI4MzRhaXR4OWJpNnUxYmU2Nmh2aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pYpRGqxq9N0oE/giphy.gif" />

If you give me a few minutes I can help with this.

Am I OK assuming you need a SVG file that includes those gradients?

PS: Nice work on the new website. Looks very neat 🚀

**Comment by lhein** [comment]
Any help is very appreciated! Thanks for jumping in!

**Comment by lordrip** [comment]
That would be beyond great, thanks a lot @d4n1b

**Comment by d4n1b** [comment]
Mmm... @lhein / @lordrip I noticed that the original logo has letters in it.

Do you want me to add "Kaoto" to the SVG as well? - ATM, I've only done the camel 

**Source code**
![image](https://github.com/KaotoIO/kaoto/assets/17992718/c5036b8c-c394-483f-b0b6-74cd7e06672c)

vs

**My SVG redesign**
![image](https://github.com/KaotoIO/kaoto/assets/17992718/45522788-e507-42b0-848d-2194cd7cece9)

**Comment by lhein** [comment]
I love it. Having that Camel as SVG is already awesome. If you want to you could contribute a second SVG with the text.

**Comment by lordrip** [comment]
What was the font used?

**Comment by lhein** [comment]
Bitstream Vera Sans Roman or similar
