### ISSUE TITLE
data format and expression typeahead unknown value issue

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1200]
### Describe the Bug

In case the e.g. data format or expression typeahead is used for filtering and unknown value is inserted, once the "no results found" field is clicked, there is a message in the sidebar "This node cannot be configured yet"

### Steps to Reproduce the Bug or Issue

1. in expression or data format typeahead field type unknown value
2. click the "no results found" message
3. see the "This node cannot be configured yet" message

### Screenshots or Videos

https://github.com/KaotoIO/kaoto/assets/4180208/8673ad04-a9eb-46ce-8482-b1ed38a823e3

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
When clicking on "Not found" shouldn't trigger a selection.
