### ISSUE TITLE
Filtering string with empty space not working

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1207]
### Describe the Bug

When filtering e.g. on Log step - the "show all" string should have two results, but in reality doesn't show any results.

### Steps to Reproduce the Bug or Issue

1. use log step
2. type "show all" into filter
3. see no results are displayed

### Screenshots or Videos

https://github.com/KaotoIO/kaoto/assets/4180208/134b233f-d554-4424-9a6f-3edaace25ee1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
This is happening since we're only filtering by property name and should also include title.
