### ISSUE TITLE
Kaoto version 2.1.0. missing in the Kaoto operator

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1383]
### Describe the Bug

The Kaoto operator doesn't provide an option to install version 2.1.0., even though this version was released some time ago.

![Screenshot from 2024-09-04 14-38-56](https://github.com/user-attachments/assets/cdade064-f04b-4fd8-a475-9e6df39ac97a)

### Steps to Reproduce the Bug or Issue

1. go to openshift Operatorhub
2. select the Kaoto operator
3. see missing Kaoto version

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by oscerd** [comment]
This could be done on the kaoto-operator side, if we all agree

**Comment by lordrip** [comment]
@tplevko after the recent release, is this fixed?

**Comment by lhein** [comment]
![Image](https://github.com/user-attachments/assets/6db4cea6-c702-4c3f-b50d-dc00c8a42590)

**Comment by lhein** [comment]
I am wondering why we still use that crappy old Kaoto logo. Can we use the new one instead?

**Comment by apupier** [comment]
> I am wondering why we still use that old Kaoto logo. Can we use the new one instead?

reported https://github.com/KaotoIO/kaoto/issues/1421
