### ISSUE TITLE
Wrong speling of SpringBoot in Catalog

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1391]
### Describe the Bug

Wrong speling of SpringBoot in Catalog, it is written without space SpringBoot

### Steps to Reproduce the Bug or Issue

1. Open file
2. Click on catalog dropdown

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Here's an screenshot
![Image](https://github.com/user-attachments/assets/24477595-7e03-45d1-8b83-93de965172a8)

**Comment by lordrip** [comment]
Changes:
1. Change the name in the Catalog generator
2. Change the UI part that checks for Spring boot
3. Rebuild the existing catalogs
