### ISSUE TITLE
Embed more Camel Catalog versions by default

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1392]
### Please describe the feature that you want to propose

Currently there is only latest community version.

I think we should have:
* latest community version at time of release
* latest LTS community version at time of release
* Red Hat supported versions

**Comment by lordrip** [comment]
Putting it on hold as we need the `--json` output from the Camel CLI

**Comment by apupier** [comment]
I think it would be better to have the list manually maintained. If using an automated way, if there is a release of Camel right before the Kaoto release it will pick it without further testing.

**Comment by apupier** [comment]
would be convenient to have https://github.com/KaotoIO/kaoto/issues/1597 fixed to implement this one. But there is a workaround by providing a settings;xml with Red Hat Maven repository

**Comment by apupier** [comment]
I do not find find where/how the catalog is generated. Seems currently like the version picked depends on the version defined as dependency in the pom.xml currently, this is not parameters provided somewhere else
