### ISSUE TITLE
Config panel buttons All is overlayed when the config panel is relatively small

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1422]
### Describe the Bug

Config panel pbuttons All is overlayed when the config panel is relatively small, even if some places is still available

### Steps to Reproduce the Bug or Issue

1. Create a route
2. select a component
3. slightly reduce the size of the config panel

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/4add28cd-4ab2-4074-b534-9b15e8cd18ac)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Thanks @tplevko for taking care
