### ISSUE TITLE
Remove menu items that does not work in the online editor

### ISSUE THREAD

**Issue by davsclaus** [KaotoIO/kaoto#1444]
### Please describe the feature that you want to propose

In the left hand side menu

- rest
- metadata
- pipe error handler

does not work/fail - remove them.

When using
https://kaotoio.github.io/kaoto/#/

**Comment by lordrip** [comment]
We're gonna remove `Rest` and for the `Metadata` and `PipeErrorHandler` will be only visible when working with Kamelets and Pipes
