### ISSUE TITLE
Set the stable checkbox in the release pipeline workflow as true by default

### ISSUE THREAD

**Issue by oscerd** [KaotoIO/kaoto#1458]
### Please describe the task that needs to be done

This will avoid problems in case of forgetting to set it

**Comment by oscerd** [comment]
If you don't set the stable version in the kaoto release, you cannot release the operator, because you won't have a stable image, so you will end up using the old stable.

**Comment by oscerd** [comment]
I think @lordrip could help in the discussion.

**Comment by lordrip** [comment]
@lhein, that's correct. We could forget about unchecking the option, but at the moment, the effects of not releasing the operator are more problematic than those of releasing a potentially unstable one. :thinking:

**Comment by lhein** [comment]
leaving that decision to you guys
