### ISSUE TITLE
Kamelets not sorted alphabetically in the catalog

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1472]
### Describe the Bug

The Kamelet catalog doesn't sort the provided kamelets alphabetically. The current order doesn't seem to have any specific rule.

### Steps to Reproduce the Bug or Issue

1. go to the catalog
2. select the kamelets
3. see the order is not alphabetical 

### Screenshots or Videos

![Screenshot from 2024-09-25 09-39-39](https://github.com/user-attachments/assets/264c7b1a-1dcb-4853-aada-1eae79da56c3)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
I checked the generated catalog and the JSON file is generated without order, so this needs to be checked at the `catalog-generator` package.

Maybe is just a matter of setting the right sorted for the `ObjectMapper` when writing the file:
```java
        ObjectMapper jsonMapper = new ObjectMapper()
                .configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
```

Here's an example: https://github.com/KaotoIO/kaoto/blob/458400e345739b368aa10732d1b7a80368070b32/packages/catalog-generator/src/main/java/io/kaoto/camelcatalog/commands/GenerateCommand.java#L63-L64
