### ISSUE TITLE
Missing validation error message for numeric inpouts

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1544]
### Describe the Bug

When validating numeric fields, there's no error message in the configuration form.

### Steps to Reproduce the Bug or Issue

 1

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/ec10414d-353f-4060-8537-09c798f52330)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Thanks @d4n1b for catching this

**Comment by d4n1b** [comment]
No worries! I created another PR to add a small test coverage
