### ISSUE TITLE
Route label is not respecting the settings to display id or description

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1581]
### Describe the Bug

Route label is not respecting the settings to display id or description; it always display the description when there is one

### Steps to Reproduce the Bug or Issue

1. create a route
2. change settings to display id for nodes
3. select route and provide a description
4. click elsewheree so that changes are applied
5. --> the route label is using the description

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by shivamG640** [comment]
Also check for Containers!
