### ISSUE TITLE
Error handler - all error handlers configurations visible by default

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1590]
### Describe the Bug

In the error handler, there used to be a dropdown, where the user selected single type of error handler. Now the error handler provides by default all the configurations for all the error handler types plus the dropdown with the error handler selection.

### Steps to Reproduce the Bug or Issue

1. create error handler
2. open the config tab
3. see there are all the error handler types configurable by default

### Screenshots or Videos

current state:

https://github.com/user-attachments/assets/96f4ecb9-8db8-4982-94c4-6aa6875bc424

In the past:
![Screenshot from 2024-10-25 09-57-07](https://github.com/user-attachments/assets/0d92544e-77e8-4e6f-beee-190a813d7f66)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
This issue is present in [the general Kaoto catalog](https://github.com/KaotoIO/catalogs), the fix is to update the catalogs to include the improvements done over the `oneOf` handling.
