### ISSUE TITLE
Manually configure the list of components displayed by the specified processor

### ISSUE THREAD

**Issue by longhai-he** [KaotoIO/kaoto#1689]
### Please describe the feature that you want to propose
Camel Version 4.8.1   Kaoto Version 2.3.0

Can I dynamically specify the names of the components processors want to display?  For example, I only want to use setBody, setHeader, loop, etc. in the processor, not display all the components

At present, I have made some attempts by myself, as shown below
<img width="746" alt="1" src="https://github.com/user-attachments/assets/bdb6eeaa-1b2d-4e75-900e-43ab7cf7d1fb">
<img width="813" alt="2" src="https://github.com/user-attachments/assets/342546e5-8660-4ea2-aefe-ad6472c79b1c">
<img width="747" alt="3" src="https://github.com/user-attachments/assets/4ebfbf0d-88c1-4356-955b-7d6085c3f662">

Desired effect
If you modify the corresponding JSON file, you can control the number of processors displayed. Is it feasible

Status quo
After modifying the JSON file, it is possible to show the processors specified, but the verification mechanism is triggered when the component is added, as shown in Figure 1

**Comment by lordrip** [comment]
Hi @longhai-he, you can do that but please keep the `to` EIP since that's the EIP that leverages the Camel components.

That being said, could you please expand a bit in your use case? For instance, what are you trying to achieve?

**Comment by longhai-he** [comment]
Thank you for your reply 
<img width="884" alt="4" src="https://github.com/user-attachments/assets/2d69cefd-4d07-4580-bce1-063350385c57">
As shown in the figure, there are 72 processors, but I only want to specify a few of them to show, such as setBody, setHeader, loop, and so on, while the others are hidden

**Comment by longhai-he** [comment]
@lordrip hello
The exception message is: The confiquration for an unknown node cannot be
changed in the confiquration form.  Please switch to
the source code and correct the node type.  Another
option is to replace the step in the qraphical editor but
in that case you will probably lose the existing
confiquration.

In fact, the goals I want to achieve are different, which have been achieved, but it only leads to another abnormal problem, which directly makes me unable to use Kaoto orchestration components, so I would like to ask if there is no direct modification to achieve my goals without affecting the existing functions


The predicted cause triggered the check and became unavailable
<img width="1246" alt="8" src="https://github.com/user-attachments/assets/f7a42d24-32be-4874-8e9d-cfd00b12d747">
<img width="1076" alt="9" src="https://github.com/user-attachments/assets/938d490d-d4f2-48f7-8862-e0591645e6f2">

**Comment by lhein** [comment]
@longhai-he you have removed the `to` EIP/Processor and that is used for all the components (also http). Add it back and it maybe already solves the problem.

**Comment by longhai-he** [comment]
@lhein  Hi, I don't think so, because I have reservations about the https component
<img width="767" alt="7" src="https://github.com/user-attachments/assets/615c4daa-05ed-4a37-8ff7-84b4a1c1fb9c">

**Comment by lhein** [comment]
What we tried to outline is something different. The following should be there in your catalog to make it work:
![grafik](https://github.com/user-attachments/assets/1dae7baf-3e7f-46be-af71-1c8dcc0f3297)

**Comment by longhai-he** [comment]
@lhein Thanks for your support. According To your plan, the TO and ToD Processor are retained and can be used normally now

**Comment by longhai-he** [comment]
Summary of the issue: Camel Version: 4.8.1 Kaoto Version: 2.3.0 Objective: To customize the display of components and processors by trimming the lists using the existing resources in Kaoto. Process: Modify the files camel-catalog-aggregate-components-a681d5b9e4745907136a96019ddd169c.json and camel-catalog-aggregate-patterns-c4714ba110bbc2ee504438d555ca996f.json. Note that the file names may vary with different Camel versions as the suffixes are different.

Translation to English: Issue Summary: Camel Version: 4.8.1 Kaoto Version: 2.3.0 Goal: To utilize Kaoto’s existing resources to tailor the list of components and processors for a customized display. Procedure: Modify the files camel-catalog-aggregate-components-a681d5b9e4745907136a96019ddd169c.json and camel-catalog-aggregate-patterns-c4714ba110bbc2ee504438d555ca996f.json. Please note that the file names differ for various Camel versions as the suffixes are not consistent.

**Comment by lhein** [comment]
You can also think about creating your own Kaoto Catalog and use that in the UI instead.
Check out [Docs](https://kaoto.io/docs/manual/generating-catalog/) for more information. It might be not up2date but it should give you some idea of how to do it.

**Comment by longhai-he** [comment]
It's a good idea, and I'm doing it now
