### ISSUE TITLE
Mask sensitive configuration values

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto#285]
### Please describe the feature that you want to propose

The camel catalog provides the information on each config parameter if it contains sensitive information or not via the attribute `secret`. If that attribute is set to `true` we should put a mask on the input field. (PF5 has ready to use component for such cases)

**Comment by lhein** [comment]
This needs further investigation as usually users would not put in a password directly but rather reference a secret or property holding that value.

**Comment by lhein** [comment]
https://www.patternfly.org/components/password-generator

**Comment by igarashitm** [comment]
What do we want to do for when a user wants to put a property placeholder? we should somehow provide a way to disable the masking for that.

**Comment by lhein** [comment]
with the password generator from PF users can toggle visibility. Maybe that is enough?
