### ISSUE TITLE
Introduce containers in the canvas for branches

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto#368]
We had that feature in our old Eclipse tooling. This issue is also related to the Collapse / Expand feature described in #367 .

Todo:
- [ ] Provide `CustomGroup` component (https://github.com/KaotoIO/kaoto/pull/1289)
- [ ] Enable groups on branches

### Screenshot
![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/773c0339-2cbf-4f1d-9159-b59c6fa1673c)

**Comment by lordrip** [comment]
Here's my proposal on how to move forward with this:
1. Add a container for individual routes only
2. Add the underlying element to be configured in the Canvas Form
3. Add containers for branches
4. Evaluate whether we need configuration for those containers as well or not
