### ISSUE TITLE
Sort language/dataformat properties with catalog index order

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#440]
### Please describe the task that needs to be done

Currently it is sorted alphabetically and keep required fields upper. Since Camel catalog has indexes explicitly, it would be better to use that order instead.

https://github.com/KaotoIO/kaoto-next/blob/90d64822abb0d6f055606d23258bef9ac23ee88a/packages/ui/src/components/MetadataEditor/MetadataEditor.tsx#L133-L140

**Comment by lordrip** [comment]
This could be done at the plugin side, like we're doing for entities and EIPs

**Comment by tplevko** [comment]
@igarashitm could you please provide more details for this issue? I'm not sure whether it's related to the `language/dataformat` components properties as mentioned in the title, or it's related to `MetadataEditor`, as mentioned in the code sample attached to the issue.
Any additional information for this issue will be highly appreciated. Thanks.

**Comment by tplevko** [comment]
I don't seem to be able to find the explicit indexes for the metadata editor in the Camel catalog. The indexes are not present for the metadata entries: 
[kubernetes-api-v1-openapi-ObjectMeta-f47bc9eaeb6490c47eefce9681226fee.json](https://github.com/user-attachments/files/17159953/kubernetes-api-v1-openapi-ObjectMeta-f47bc9eaeb6490c47eefce9681226fee.json)
