### ISSUE TITLE
Reusable Visualization

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto#472]
### Please describe the feature that you want to propose

It'd be nice to being able to reuse existing canvas in the hawtio to retain the consistent look and feel from design time to runtime/debug. 

Considering current state of kaoto and hawtio one of the easiest ways could be to share only the canvas with icons and keep the logic of parsing the running routes and creating nodes and edges on the hawtio side.

### Related PRs:
* https://github.com/KaotoIO/kaoto/pull/1319
* https://github.com/KaotoIO/kaoto/pull/1403
* https://github.com/KaotoIO/kaoto/pull/1426

**Comment by lordrip** [comment]
In `kaoto-next` we have the following layers:

1. Camel Resource (
2. Camel Visual Entity (might be an individual Camel Route, the flow part of a Kamelet or Pipe)
3. VisualizationNodes (Represent the flow tree)
4. Canvas nodes (Canvas nodes, representing their underlying VIsualization nodes)

# 4 is what's closer to the Canvas itself.

The first thing to identify is at which level we want to integrate.

**Comment by lordrip** [comment]
This is also waiting for HawtIO patternfly upgrade to v5

**Comment by lordrip** [comment]
Thanks @mmelko for your services :D :saluting_face:
