### ISSUE TITLE
Export TypeScript definitions for @kaoto-next/camel-catalog

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#5]
### Please describe the feature that you want to propose

Currently, there are no TypeScript definitions for the catalog, meaning that all the information is typed as `any`, defeating the static checks' purpose.

**Comment by igarashitm** [comment]
like this - https://www.npmjs.com/package/json-schema-to-typescript

**Comment by lordrip** [comment]
Actually, I was aiming at the catalog index itself :smile:, you know, the `index.json` file that we create.

**Comment by lordrip** [comment]
This has been partially implemented [here](https://github.com/KaotoIO/kaoto-next/blob/main/packages/camel-catalog/src/json-schema-to-typescript.mts#L55), what's remaining is to pass the generated `index.json` as well, but I'm not sure if the same library would work as it is or if we would need something different.
