### ISSUE TITLE
Support masking `password` type field

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#503]
### Please describe the feature that you want to propose

cf. https://github.com/KaotoIO/kaoto-next/pull/497#issue-2025103501

Some of the official kamelets have `format: password` in its parameter definition. It is already passed into `propertiesSchema` in Kaoto.

However, uniforms seems not leverage it to make `TextInput` to have `type=password`.
https://github.com/KaotoIO/uniforms-patternfly/blob/081136eb61576f18b7bb437bb01ec29b901ce066/src/TextField.tsx#L118-L126
 Here it should do
```typescript
if (props.field.format === 'password') return 'password'
```

**Comment by lhein** [comment]
related to #285  ?

**Comment by lordrip** [comment]
Yes, related

**Comment by lhein** [comment]
https://www.patternfly.org/components/password-generator
