### ISSUE TITLE
Support copy&paste for steps, branches and whole route

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#515]
### Please describe the feature that you want to propose

Support copy an existing step node, branch or a whole route on the canvas, and paste it. This improves the usability and productivity.

**Comment by lhein** [comment]
Also think about key bindings. CTRL+C / CTRL+V

**Comment by lhein** [comment]
Don't forget to take care of making unique IDs.

**Comment by lhein** [comment]
relates to #1479 
relates to #1480

**Comment by lhein** [comment]
this issue duplicates 2 existing issues I linked above. Closing this one.
