### ISSUE TITLE
LoadBalancer steps shown in canvas in linear way

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#648]
### Please describe the feature that you want to propose

The LoadBalancer node currently displays it's steps in the route canvas in linear way.

To make it more clear for the users, that the nodes are in reality steps, used for load balancing, it would be useful to show these as LoadBalancer nodes. Similar to the way, this was displayed in the old UI (screenshot attached).

https://github.com/KaotoIO/kaoto-next/assets/4180208/5af19742-cf62-4b57-804f-f3b7d65868cd

![Screenshot from 2024-01-16 10-43-39](https://github.com/KaotoIO/kaoto-next/assets/4180208/1ee23310-c357-4aa0-8e4f-15e7ff278792)

**Comment by lordrip** [comment]
This needs #368 before this can be handled
