### ISSUE TITLE
Improve catalog filtering using tags - have separate element with filtering tags in the search

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#686]
### Please describe the feature that you want to propose

The tags in the catalogue are a useful way, how the user can filter components of interest. There could be however an enhancement for the usability - to show an element, with all the summarized filtering tags. I think this can be done in several ways, one of which I think could be placing [Faceted Filter](https://www.patternfly.org/patterns/filters#faceted-filter) with all filtering labels next to the Search Bar in the catalogue.

Current way of using the labels for filtering:
![Screenshot from 2024-01-22 10-51-17](https://github.com/KaotoIO/kaoto-next/assets/4180208/da2be6f3-b220-4c54-8eda-696b80074b32)

Faceted Filter element: 
![Screenshot from 2024-01-22 10-46-07](https://github.com/KaotoIO/kaoto-next/assets/4180208/f8b602bc-659f-4992-8d8c-837fc1804456)

**Comment by lordrip** [comment]
Oh, fancy, I like the idea @tplevko, very cool

**Comment by lhein** [comment]
Closing in favor of #1041
