### ISSUE TITLE
Provide an easy way to Disable a given step

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#699]
### Please describe the feature that you want to propose

It would be convenient to add a "Disable" node functionality in the contextual menu that sets the `Disabled` property to true/false depending on whether the node provides such a property. In addition to that, it would be nice to have a fade-down view of the icon to signal that it's disabled.

**Comment by lhein** [comment]
Is there such a property in the schema which allows to disable specific steps?

**Comment by apupier** [comment]
> Is there such a property in the schema which allows to disable specific steps?

yes

There is always a "Disabled" option:

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/aec050fc-c7ad-4504-97d9-1778fb2e0572)
