### ISSUE TITLE
Rename kaoto-next to kaoto

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto#708]
'kaoto-next' was an internal work title and I am suggesting to change it to just 'kaoto' in all places (also the repository name).

**Comment by lordrip** [comment]
The project was already renamed from `kaoto-next` to `kaoto`. The missing part is to rename the NPM package to `@kaoto/kaoto` once we're done with the 2.0 issues.

**Comment by lordrip** [comment]
This issue tackles the repository name, there's a follow-up issue #1009 to handle the npm package name.
