### ISSUE TITLE
Config form spacing improvements

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto#754]
![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/241f0428-d152-4a1b-90e7-f48b3b30e2dc)

The vertical spacing is not done in a uniform way. There are differences between the name of the step to the next label under that  and the spacing in sub forms is different to the main form. 

Can we align everything so it has a uniform look and feel?

**Comment by lordrip** [comment]
Yup, this seems very similar to https://github.com/KaotoIO/kaoto-next/issues/695, which @shivamG640 is looking already 💪

**Comment by lordrip** [comment]
Closing it as this was taken care of by the changes in the `uniforms-patternfly` library.
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/a6df3a54-8b67-40b2-9b1a-a313f2d6b227)
