### ISSUE TITLE
Unable to click the 3 dots menu next to the step label if the label length is bigger than what can be displayed

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#789]
### Describe the Bug

The option to expend the dropdown is displayed, when the name is shrunken, however, the dropdown can't be opened, as after the mouse hover on the three dots the name gets expanded. 

### Steps to Reproduce the Bug or Issue

1. add node, which name "shrinks", e.g. twitter-timeline-source
2. try to click the dropdown, when the name is not expanded

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/4180208/380c4a2f-db2e-471d-a7d2-af7ea46801a0

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lhein** [comment]
we should limit the length of the label on the canvas and add a `...` if its longer. Lets limit it to 15 char + the 3 `...` for a first iteration.
