### ISSUE TITLE
Provide `route` name in `direct` node's label

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#814]
### Please describe the feature that you want to propose

In the case of a `direct` node, it would be beneficial to see the actual `route` name in the label.

In the following screenshot, the `name`'s property value is `start2`, then the label could be `direct: start2`

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/28f0e3cd-83d9-4159-ab56-a50d06e7086b)

**Comment by lhein** [comment]
Just keep in mind that this is not the route name but the destination name for the direct endpoint. Your first route could for instance end with a direct endpoint called `msgBox` and then when defining your next new route you could start with another direct endpoint with the same name `msgBox` which would basically connect both routes. For such cases it would also make sense to pre-populate the name field (as drop down with direct edit capabilities) with all found direct endpoint names over all the routes. (consolidated to only have unique names) In a next step we could draw a connection between connected routes.

**Comment by lordrip** [comment]
Raising the priority since it's a enhancement for visualization purposes

**Comment by lhein** [comment]
Can we create a function that takes a step and then decides what to display individually for each step. Additionally whenever a "description" has been provided for a step, we should use the description instead.

**Comment by lordrip** [comment]
Yes, we have it already, [it's here](https://github.com/KaotoIO/kaoto/blob/9be2b962e3742f32949c96a8602637d017860874/packages/ui/src/models/visualization/flows/support/camel-component-schema.service.ts#L90-L111), it's just a matter of extending it to provide more tailored information.
