### ISSUE TITLE
Catalog layout select button partially hidden

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#911]
### Describe the Bug

When opening the catalog - the layout change button is partially hidden.

### Steps to Reproduce the Bug or Issue

1. open the catalog
2. see in top right corner

### Screenshots or Videos

![Screenshot from 2024-03-07 11-00-08](https://github.com/KaotoIO/kaoto-next/assets/4180208/f65d62f2-b0a3-4c4d-93b9-cd3edbb02fdf)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
Fixed by https://github.com/KaotoIO/kaoto/pull/1078
