### ISSUE TITLE
`ExpressionField` shows not configured for expressionless languages

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#965]
### Describe the Bug

Both `Tokenize` and `Beans` languages don't have an `Expression` field, hence, the Expression launcher shows not configured
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/59b0d874-d35d-477e-a6a1-db9c823bbdb7)

### Steps to Reproduce the Bug or Issue

1. Introduce a Spli EIP
2. Configure a `Tokenize` expression
3. Close and reopen the configuration form
4. Notice how the expression field says not configured but still the Tokenize data is there.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by igarashitm** [comment]
`Bean Method` expression also hit this
