### ISSUE TITLE
Help for Properties config field in form

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#978]
### Please describe the feature that you want to propose

The properties config filed in form could contain, in case there is a description defined in the schema a help popup, similar to other fields in the form.

Properties fields (rest config):
![Screenshot from 2024-03-28 07-57-43](https://github.com/KaotoIO/kaoto-next/assets/4180208/6e5896a5-ce3b-4683-803b-fde8d9992c89)
schema (description at the end):
![Screenshot from 2024-03-28 07-57-25](https://github.com/KaotoIO/kaoto-next/assets/4180208/a6e9b907-3daa-4ba8-902b-eb187a7bfecd)

**Comment by lordrip** [comment]
This would be a nice addition @tplevko :+1: , this needs to be handled in the https://github.com/KaotoIO/uniforms-patternfly repository in the same fashion as we're doing it for TextField
